FROM almalinux:9.3 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

COPY bgMerginFilename.sh /bin/bgMerginFilename.sh
COPY localSetupBase.sh /app/localSetup.sh

# JLab certificate
ADD https://pki.jlab.org/JLabCA.crt /etc/pki/ca-trust/source/anchors/JLabCA.crt
RUN update-ca-trust

# alma specific:
# crb: for mysql-devel
# synergy: root, scons, vnc
RUN    dnf install -y  'dnf-command(config-manager)' \
    && dnf config-manager --set-enabled crb \
    && dnf install -y almalinux-release-synergy

RUN echo "export SIM_HOME=/cvmfs/oasis.opensciencegrid.org/jlab/geant4" >> /app/localSetup.sh \
    && echo "source /cvmfs/oasis.opensciencegrid.org/jlab/geant4/ceInstall/setup.sh" >> /app/localSetup.sh 


RUN dnf install -y --allowerasing  gcc-gfortran pcre-devel mesa-libGL-devel mesa-libGLU-devel glew-devel ftgl-devel mariadb-devel sqlite-devel fftw-devel cfitsio-devel graphviz-devel libuuid-devel avahi-compat-libdns_sd-devel openldap-devel python-devel python3-numpy libxml2-devel gsl-devel readline-devel qt5-qtwebengine-devel R-devel R-Rcpp-devel R-RInside-devel gcc binutils xrootd-client lsof liburing flexiblas-devel  bzip2 wget curl nano bash tcsh zsh hostname gedit environment-modules rsync patch which  \
  && dnf -y update \
  && dnf -y check-update \
  && dnf clean packages \
  && dnf clean all \
  && rm -rf /var/cache/dnf 


# Setup demo environment variables
ENV HOME=/root LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8  LC_ALL=C.UTF-8  DISPLAY=:0.0 DISPLAY_WIDTH=1400 DISPLAY_HEIGHT=1000 RUN_XTERM=yes RUN_FLUXBOX=yes

COPY fluxbox/conf.d /app/conf.d
COPY fluxbox/supervisord.conf fluxbox/entrypoint.sh  /app/

CMD ["/app/entrypoint.sh"]
EXPOSE 8080


