FROM jeffersonlab/geant4:g4v10.7.4-ubuntu24 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]
ENV AUTOBUILD 1

# JLab certificate
ADD https://pki.jlab.org/JLabCA.crt /etc/pki/ca-trust/source/anchors/JLabCA.crt
RUN echo "module load gemc/5.10" >> /etc/profile.d/localSetup.sh 


# ceInstall update  
RUN cd /cvmfs/oasis.opensciencegrid.org/jlab/geant4/modules \
    &&  git checkout nosim  \
    &&  git pull  

RUN source /etc/profile.d/localSetup.sh \
    && module use /cvmfs/oasis.opensciencegrid.org/jlab/geant4/modules \
    && module load sim_system \
    && install_gemc 5.10 \
    && install_gemc dev 

