FROM ubuntu:24.04 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

COPY localSetupBase.sh /app/localSetup.sh

# Update needed at beginning to use the right package repos
RUN  apt update

# Install ca-certificates tools
RUN apt-get install -y ca-certificates

# JLab certificate
ADD https://pki.jlab.org/JLabCA.crt /etc/pki/ca-trust/source/anchors/JLabCA.crt
RUN update-ca-certificates

RUN echo "export SIM_HOME=/cvmfs/oasis.opensciencegrid.org/jlab/geant4" >> /app/localSetup.sh \
    && echo "source $SIM_HOME/ceInstall/setup.sh" >> /app/localSetup.sh 


RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime \
    && DEBIAN_FRONTEND=noninteractive apt-get  install -y --no-install-recommends tzdata  fortran libpcre3-dev xlibmesa-glu-dev libglew-dev libftgl-dev libmysqlclient-dev libfftw3-dev libcfitsio-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python3-dev python3-numpy libxml2-dev libkrb5-dev libgsl0-dev qtwebengine5-dev nlohmann-json3-dev gcc binutils xrootd-client lsof liburing2 \
   && apt-get -y update \
   && apt-get -y autoclean

# root installed using tarball
ENV ROOT_RELEASE=6.30.04
ENV ROOT_FILE=root_v${ROOT_RELEASE}.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
ENV ROOT_INSTALL_DIR=/usr/local
RUN cd ${ROOT_INSTALL_DIR} \
    && wget https://root.cern/download/${ROOT_FILE} \
    && tar -xzvf ${ROOT_FILE} \
    && rm ${ROOT_FILE} \
    && echo "cd ${ROOT_INSTALL_DIR}/root ; source bin/thisroot.sh ; cd -" >> /etc/profile.d/root.sh

