FROM ubuntu:24.04 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]
ENV AUTOBUILD 1

COPY bgMerginFilename.sh /bin/bgMerginFilename.sh
COPY localSetupBase.sh /etc/profile.d/localSetup.sh

# JLab certificate
ADD https://pki.jlab.org/JLabCA.crt /etc/pki/ca-trust/source/anchors/JLabCA.crt
# Update needed at beginning to use the right package repos
RUN apt update

# Install ca-certificates tools
RUN apt-get install -y ca-certificates

RUN update-ca-certificates 

RUN echo "module use /cvmfs/oasis.opensciencegrid.org/jlab/geant4/modules" >> /etc/profile.d/localSetup.sh 

RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime \
    && DEBIAN_FRONTEND=noninteractive apt-get  install -y --no-install-recommends tzdata  gfortran libpcre3-dev xlibmesa-glu-dev libglew-dev libftgl-dev libmysqlclient-dev libfftw3-dev libcfitsio-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python3-dev python3-numpy libxml2-dev libkrb5-dev libgsl0-dev qtwebengine5-dev nlohmann-json3-dev gcc binutils xrootd-client lsof liburing2  bzip2 wget curl nano bash tcsh zsh hostname gedit environment-modules rsync patch 
# root installation using tarball
RUN cd /usr/local \
    && curl -S --location-trusted --progress-bar --retry 4 --cacert /etc/pki/ca-trust/source/anchors/JLabCA.crt {'https://root.cern/download/root_v6.32.02.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz'} -k -O  \
    && tar -xzvf root_v6.32.02.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz \
    && rm root_v6.32.02.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz \
    && echo "cd /usr/local/root/bin ; source thisroot.sh ; cd -" >> /etc/profile.d/localSetup.sh


# meson installation using tarball
RUN cd /usr/local \
    && curl -S --location-trusted --progress-bar --retry 4 --cacert /etc/pki/ca-trust/source/anchors/JLabCA.crt {'https://github.com/mesonbuild/meson/releases/download/1.8.2/meson-1.8.2.tar.gz'} -k -O  \
    && tar -xzvf meson-1.8.2.tar.gz \
    && rm meson-1.8.2.tar.gz \
    && ln -s /usr/local/meson-1.8.2/meson.py /usr/bin/meson


# Setup demo environment variables
ENV HOME=/root LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8  LC_ALL=C.UTF-8  DISPLAY=:0.0 DISPLAY_WIDTH=1400 DISPLAY_HEIGHT=1000 RUN_XTERM=yes RUN_FLUXBOX=yes

COPY fluxbox/conf.d /app/conf.d
COPY fluxbox/supervisord.conf fluxbox/entrypoint.sh  /app/

CMD ["/app/entrypoint.sh"]
EXPOSE 8080


