FROM jeffersonlab/geant4:g4v10.6.2-almalinux93 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]
ENV AUTOBUILD 1

RUN echo "module load gemc/4.4.2" >> /etc/profile.d/localSetup.sh 


# ceInstall update  
RUN cd /cvmfs/oasis.opensciencegrid.org/jlab/geant4/modules \
    &&  git checkout nosim  \
    &&  git pull  

RUN source /etc/profile.d/localSetup.sh \
    && module use /cvmfs/oasis.opensciencegrid.org/jlab/geant4/modules \
    && module load sim_system \
    && install_gemc 4.4.2 

