FROM ubuntu:22.04 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

# Update needed at beginning to use the right package repos
RUN  apt update

# Install ca-certificates tools
RUN apt-get install -y ca-certificates

# JLab certificate
ADD https://pki.jlab.org/JLabCA.crt /etc/pki/ca-trust/source/anchors/JLabCA.crt
RUN update-ca-certificates


RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime \
    && DEBIAN_FRONTEND=noninteractive apt  install -y --no-install-recommends tzdata  git make cmake g++ expat libexpat1-dev libmariadb-dev libsqlite3-dev python3-dev scons libglu1-mesa-dev  libx11-dev   libxpm-dev   libxft-dev    libxt-dev   libxmu-dev   libxrender-dev    xvfb                 x11-xserver-utils bzip2 wget curl nano which bash tcsh zsh hostname gedit environment-modules psmisc procps mailcap net-tools libcpandb-perl xterm x11vnc novnc fluxbox supervisor libqt5widgets5 libqt5opengl5-dev libqt5printsupport5\
	&& apt  update \
	&& apt  autoclean

