FROM ubuntu:22.04 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

COPY localSetupBase.sh /app/

# Update needed at beginning to use the right package repos
RUN  apt update

# Install ca-certificates tools
RUN apt-get install -y ca-certificates

# JLab certificate
ADD https://pki.jlab.org/JLabCA.crt /etc/pki/ca-trust/source/anchors/JLabCA.crt
RUN update-ca-certificates


RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime \
    && DEBIAN_FRONTEND=noninteractive apt-get  install -y --no-install-recommends tzdata  git make cmake g++ expat libexpat1-dev libmariadb-dev libsqlite3-dev python3-dev scons libglu1-mesa-dev  libx11-dev   libxpm-dev   libxft-dev    libxt-dev   libxmu-dev   libxrender-dev    xvfb                 x11-xserver-utils bzip2 wget curl nano bash tcsh zsh hostname gedit environment-modules psmisc procps mailcap net-tools libcpandb-perl xterm x11vnc novnc fluxbox supervisor libqt5widgets5 libqt5opengl5-dev libqt5printsupport5\
	&& apt-get -y update \
	&& apt-get -y autoclean

# root installed using tarball
ENV ROOT_RELEASE=6.30.04
ENV ROOT_FILE=root_v${ROOT_RELEASE}.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz
ENV ROOT_INSTALL_DIR=/usr/local
RUN cd ${ROOT_INSTALL_DIR} \
    && wget https://root.cern/download/${ROOT_FILE} \
    && tar -xzvf ${ROOT_FILE} \
    && rm ${ROOT_FILE} \
    && echo "cd ${ROOT_INSTALL_DIR}/root ; source bin/thisroot.sh ; cd -" >> /etc/profile.d/root.sh


# Setup demo environment variables
ENV HOME=/root LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8  LC_ALL=C.UTF-8  DISPLAY=:0.0 DISPLAY_WIDTH=1400 DISPLAY_HEIGHT=1000 RUN_XTERM=yes RUN_FLUXBOX=yes

COPY fluxbox/conf.d /app/
COPY fluxbox/supervisord.conf fluxbox/entrypoint.sh  /app/

CMD ["/app/entrypoint.sh"]
EXPOSE 8080


