FROM jeffersonlab/sim:g4v10.7.4-ubuntu24-local 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

ENV SIM_HOME /usr/local
WORKDIR $SIM_HOME

COPY localSetupSimTemplate.sh $SIM_HOME/localSetup.sh

RUN sed  -i -e "s|templateSim|$SIM_HOME|g"    $SIM_HOME/localSetup.sh \
    && echo "module load gemc/5.10" >> $SIM_HOME/localSetup.sh \
    && cp $SIM_HOME/localSetup.sh /app/localSetup.sh \
    && cp $SIM_HOME/localSetup.sh /etc/profile.d/localSetup.sh


RUN source /app/localSetup.sh \
           && module switch gemc/5.10 \
           && install_gemc 5.10 \
           && module switch gemc/dev \
           && install_gemc dev 

