FROM jeffersonlab/geant4:g4v10.7.4-almalinux94 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]
ENV AUTOBUILD=1

# ceInstall update  
RUN cd /cvmfs/oasis.opensciencegrid.org/jlab/geant4/modules \
    &&  git pull  


# coatjava dependencies installation using tarball
RUN dnf install -y --allowerasing maven jq perl-DBI perl-DBD-SQLite perl-XML-LibXML \
    && curl -L -O https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-4.0.26.zip \
    && unzip apache-groovy-binary-4.0.26.zip \
    && rm apache-groovy-binary-4.0.26.zip \
    && mv groovy-4.0.26 /usr/local/groovy \
    && ln -s /usr/local/groovy/bin/groovy /usr/bin/groovy 

RUN source /etc/profile.d/localSetup.sh \
    && module use /cvmfs/oasis.opensciencegrid.org/jlab/geant4/modules \
    && install_gemc 5.11 \
    && install_gemc 5.13 \
    && install_gemc dev 

RUN echo "module load gemc/dev" >> /etc/profile.d/localSetup.sh
