FROM ubuntu:24.04 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]
ENV AUTOBUILD 1

COPY bgMerginFilename.sh /bin/bgMerginFilename.sh
COPY localSetupBase.sh /etc/profile.d/localSetup.sh

# Update needed at beginning to use the right package repos
RUN apt update

# Install ca-certificates tools
RUN apt-get install -y ca-certificates

# JLab certificate
ADD https://pki.jlab.org/JLabCA.crt /etc/pki/ca-trust/source/anchors/JLabCA.crt
RUN update-ca-certificates 


RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime \
    && DEBIAN_FRONTEND=noninteractive apt-get  install -y --no-install-recommends tzdata  git make cmake g++ expat libexpat1-dev libmysqlclient-dev libsqlite3-dev python3-dev scons ninja-build libglu1-mesa-dev  libx11-dev   libxpm-dev   libxft-dev    libxt-dev   libxmu-dev   libxrender-dev    xvfb                 x11-xserver-utils bzip2 wget curl nano bash tcsh zsh hostname gedit environment-modules psmisc procps mailcap net-tools rsync patch libcpandb-perl xterm x11vnc novnc fluxbox supervisor libqt5widgets5 libqt5opengl5-dev libqt5printsupport5
# root installation using tarball
RUN cd /usr/local \
    && wget https://root.cern/download/root_v6.30.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz \
    && tar -xzvf root_v6.30.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz \
    && rm root_v6.30.04.Linux-ubuntu22.04-x86_64-gcc11.4.tar.gz \
    && echo "cd /usr/local/root/bin ; source thisroot.sh ; cd -" >> /etc/profile.d/localSetup.sh


# meson installation using tarball
RUN cd /usr/local \
    && wget https://github.com/mesonbuild/meson/releases/download/1.5.0/meson-1.5.0.tar.gz \
    && tar -xzvf meson-1.5.0.tar.gz \
    && rm meson-1.5.0.tar.gz \
    && ln -s /usr/local/meson-1.5.0/meson.py /usr/bin/meson


# Setup demo environment variables
ENV HOME=/root LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8  LC_ALL=C.UTF-8  DISPLAY=:0.0 DISPLAY_WIDTH=1400 DISPLAY_HEIGHT=1000 RUN_XTERM=yes RUN_FLUXBOX=yes

COPY fluxbox/conf.d /app/conf.d
COPY fluxbox/supervisord.conf fluxbox/entrypoint.sh  /app/

CMD ["/app/entrypoint.sh"]
EXPOSE 8080


