FROM ubuntu:22.04 
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

# Update needed at beginning to use the right package repos
RUN apt-get install -y ca-certificates
